name: send-pretty-slack-message
description: send pretty slack message
inputs:
  message:
    description: 'message'
    required: true
    default: 'empty message'
  webhook-url:
    description: 'webhook url'
    required: true
    default: ''
  image:
    description: 'Image'
    required: true
    default: ''
  image-alt:
    description: 'image alt'
    required: true
    default: ''

runs:
  using: "composite"
  steps:

    - shell: bash
      run: |
        export TZ=America/Argentina/Buenos_Aires
        echo DATE_TIME=$(date +"%F %H:%M") >> $GITHUB_ENV

    - name: send json to slack
      uses: slackapi/slack-github-action@v1.18.0
      with:
        payload: |
          {
            "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "${{ inputs.message }}"
                }
              },
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "*Fecha y hora:*\n${{ env.DATE_TIME }}\n*Repositorio:*\n<https://github.com/${{ github.repository_owner }}/${{ github.event.repository.name }}|${{ github.event.repository.name }}>"
                },
                "accessory": {
                  "type": "image",
                  "image_url": "${{ inputs.image }}",
                  "alt_text": "${{ inputs.image_alt }}"
                }
              },
              {
                "type": "actions",
                "elements": [
                  {
                    "type": "button",
                    "text": {
                      "type": "plain_text",
                      "emoji": true,
                      "text": "Ver detalle"
                    },
                    "style": "primary",
                    "url": "https://github.com/${{ github.repository_owner }}/${{ github.event.repository.name }}/actions/runs/${{ github.run_id }}"
                  }
                ]
              }
            ]
          }
      env:
        SLACK_WEBHOOK_URL: ${{ inputs.webhook-url }}
        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
